# SITE CONFIGURATION
title: 기술블로그             
   # your site title
author: (주) 디거 # You :P
description: > # Meta description of Homepage
  (주) 디거의 기술 개발 블로그입니다.
  
url: "http://tech.digger.works" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: (주) 디거
  links:
    - https://www.facebook.com/publicdigger

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  

hero_img: posts/background.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: support@digger.works # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  digger-dev # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
facebook_username: publicdigger

disqus:
  shortname: Digger Blog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem

exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
